// Package minimax implements the MiniMax provider adapter.
//
// MiniMax exposes an Anthropic-messages compatible API. When used with OpenClaw's
// minimax-portal provider, the auth header is generated by OpenClaw's OAuth flow
// (from ~/.openclaw/agents/main/agent/auth-profiles.json) and forwarded as-is —
// krouter acts as a transparent proxy, not a key-injection layer.
//
// Upstream endpoint: https://api.minimaxi.com/anthropic
// (Without the trailing /v1 — the request path already carries /v1/messages.)
package minimax

import (
	"net/http"
	"strings"
	"sync"
	"time"

	anthropicAdapter "github.com/kinthaiofficial/krouter/internal/providers/anthropic"
)

// baseURL is the upstream root without a trailing path segment.
// Incoming request paths (/v1/messages, /v1/models) are appended verbatim.
const baseURL = "https://api.minimaxi.com/anthropic"

var supportedModels = []string{
	"MiniMax-M2.7",
	"MiniMax-M2.7-highspeed",
}

// cachedTokenTTL bounds how long an observed OAuth token stays usable by the
// quota poller. This in-memory retention is a documented exception to D-003
// (see DECISIONS.md): the poller cannot call token_plan/remains without it.
// The TTL keeps a rotated/stale token from being replayed indefinitely —
// any new MiniMax request refreshes the cache.
const cachedTokenTTL = 30 * time.Minute

// tokenCache holds the most recently seen OAuth Bearer token for MiniMax.
// Used by QuotaPoller to call token_plan/remains. Never persisted to disk.
var tokenCache struct {
	mu       sync.RWMutex
	token    string
	cachedAt time.Time
}

// CacheOAuthToken stores the most recently observed MiniMax OAuth token in memory.
// Called by the proxy on each MiniMax request. Token is never written to disk or logs.
func CacheOAuthToken(authHeader string) {
	token := strings.TrimPrefix(authHeader, "Bearer ")
	token = strings.TrimSpace(token)
	if token == "" || token == authHeader {
		return
	}
	tokenCache.mu.Lock()
	tokenCache.token = token
	tokenCache.cachedAt = time.Now()
	tokenCache.mu.Unlock()
}

// GetCachedToken returns the most recently cached OAuth token, or "" when
// none was seen yet or the cached one is older than cachedTokenTTL.
func GetCachedToken() string {
	tokenCache.mu.RLock()
	defer tokenCache.mu.RUnlock()
	if tokenCache.token == "" || time.Since(tokenCache.cachedAt) > cachedTokenTTL {
		return ""
	}
	return tokenCache.token
}

// ResetCachedToken clears the in-memory OAuth token. Used by tests.
func ResetCachedToken() {
	tokenCache.mu.Lock()
	tokenCache.token = ""
	tokenCache.cachedAt = time.Time{}
	tokenCache.mu.Unlock()
}

// New creates a MiniMax provider adapter that transparently proxies requests,
// preserving all headers (including OAuth tokens generated by OpenClaw).
// If client is nil, a default streaming-safe client is used.
func New(client *http.Client) *anthropicAdapter.Adapter {
	return anthropicAdapter.NewNamed("minimax", baseURL, supportedModels, client)
}
