// Package minimax implements the MiniMax provider adapter.
//
// MiniMax exposes an Anthropic-messages compatible API. When used with OpenClaw's
// minimax-portal provider, the auth header is generated by OpenClaw's OAuth flow
// (from ~/.openclaw/agents/main/agent/auth-profiles.json) and forwarded as-is —
// krouter acts as a transparent proxy, not a key-injection layer.
//
// Upstream endpoint: https://api.minimaxi.com/anthropic
// (Without the trailing /v1 — the request path already carries /v1/messages.)
package minimax

import (
	"net/http"

	anthropicAdapter "github.com/kinthaiofficial/krouter/internal/providers/anthropic"
)

// baseURL is the upstream root without a trailing path segment.
// Incoming request paths (/v1/messages, /v1/models) are appended verbatim.
const baseURL = "https://api.minimaxi.com/anthropic"

var supportedModels = []string{
	"MiniMax-M2.7",
	"MiniMax-M2.7-highspeed",
}

// New creates a MiniMax provider adapter that transparently proxies requests,
// preserving all headers (including OAuth tokens generated by OpenClaw).
// If client is nil, a default streaming-safe client is used.
func New(client *http.Client) *anthropicAdapter.Adapter {
	return anthropicAdapter.NewNamed("minimax", baseURL, supportedModels, client)
}
