import { describe, it, expect, vi, beforeEach } from 'vitest'
import { screen, waitFor, fireEvent } from '@testing-library/react'
import { renderWithProviders } from './helpers'
import Logs from '../pages/Logs'

const makeLogs = (n: number) =>
  Array.from({ length: n }, (_, i) => ({
    id: `log${i}`,
    ts: new Date().toISOString(),
    agent: i % 2 === 0 ? 'openclaw' : 'cursor',
    protocol: 'anthropic',
    model: i % 2 === 0 ? 'claude-haiku-4-5' : 'claude-sonnet-4',
    provider: 'anthropic',
    input_tokens: 100 + i,
    output_tokens: 50,
    cost_usd: 0.001 * (i + 1),
    latency_ms: 200,
    status_code: 200,
  }))

beforeEach(() => {
  vi.stubGlobal('fetch', vi.fn().mockResolvedValue({
    ok: true,
    status: 200,
    json: () => Promise.resolve(makeLogs(5)),
  }))
})

describe('Logs page', () => {
  it('renders log table after data loads', async () => {
    renderWithProviders(<Logs />)
    await waitFor(() => {
      // Multiple openclaw rows are expected (generated by makeLogs).
      expect(screen.getAllByText('openclaw').length).toBeGreaterThan(0)
    })
  })

  it('search filters results client-side', async () => {
    renderWithProviders(<Logs />)
    await waitFor(() => screen.getAllByText('openclaw'))

    const input = screen.getByPlaceholderText(/search/i)
    fireEvent.change(input, { target: { value: 'haiku' } })

    await waitFor(() => {
      expect(screen.getAllByText('claude-haiku-4-5').length).toBeGreaterThan(0)
      expect(screen.queryByText('claude-sonnet-4')).not.toBeInTheDocument()
    })
  })

  it('shows empty state for no results', async () => {
    vi.stubGlobal('fetch', vi.fn().mockResolvedValue({
      ok: true, status: 200, json: () => Promise.resolve([]),
    }))
    renderWithProviders(<Logs />)
    await waitFor(() => {
      expect(screen.getByText('No records found.')).toBeInTheDocument()
    })
  })

  it('export CSV button is present', async () => {
    renderWithProviders(<Logs />)
    await waitFor(() => screen.getAllByText('openclaw'))
    expect(screen.getByText('Export CSV')).toBeInTheDocument()
  })
})
